services:
  caddy:
    image: caddy:2-alpine
    container_name: minute_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - minute_internal

volumes:
  caddy_data:
  caddy_config:

networks:
  minute_internal:
    external: true
